# This Dockerfile only for GH action runs and performs:
#   1) Code lint checking
#   2) Runs tests from tests/
#
# Author: Abhishek Sriram <noobsiecoder@gmail.com>
# Date:   Aug 20th, 2025
# Place:  Boston, MA

# Image (OS) type
FROM ubuntu:22.04

# Prevent interactive prompts + added Time Zone
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Install build dependency tools
RUN apt-get update && apt-get install -y \
    curl \
    python3 \
    python3-pip \
    iverilog \
    yosys \
    && apt-get clean

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

# Work directory of the application
WORKDIR /src
# Copy from source to src/
COPY . .

# Install python dependencies
RUN uv sync

# Make script executable
RUN chmod +x scripts/ci.sh

# Runner/Executable point
CMD ["./scripts/ci.sh"]
