# This is the main workflow file for triggering GitHub Actions
#
# Author: Abhishek Sriram <noobsiecoder@gmail.com>
# Date:   Aug 20th, 2025
# Place:  Boston, MA

# This is the main workflow
# It handles both deploy.yaml and integrate.yaml
# Functionalities:
# deploy.yaml     -> Deploys repo to cloud and perform RLFT
# integrate.yaml  -> Performs testing before deployment
name: main-workflow

# Trigger on push to specific branch: "enhance-v1" for now
# NOTE: Only triggers when dataset/testbench/hdlbits/... is modified
on:
  push:
    branches:
      - enhance-v1 # specific branch
    # paths:
    #   - "dataset/testbench/hdlbits/**" # specific path

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Integrate and Deploy
        uses: actions/checkout@v4

      - name: Pilot run of "Dockerfile.ci"
        run: docker build -f Dockerfile.ci -t verilog-llm .

      - name: Run tests
        run: docker run verilog-llm
      
      # Step 1: Install required packages

      # Step 2: Check code lint

      # Step 3: Run Tests in tests/

      # Step 4: Run Tests

      # Step 5: Ping cloud provider via API and check available credits
      # NOTE: skip job schedule only when:
      #   1) Usage above limit.
      #   2) Resource not available.

      # Step 5: Schedule Job
