# This is the main workflow file for triggering GitHub Actions
#
# Author: Abhishek Sriram <noobsiecoder@gmail.com>
# Date:   Aug 20th, 2025
# Place:  Boston, MA

# This is the main workflow
# It handles both deploy.yaml and integrate.yaml
# Functionalities:
# deploy.yaml     -> Deploys repo to cloud and perform RLFT
# integrate.yaml  -> Performs testing before deployment
name: main-workflow

# Trigger on push to specific branch: "enhance-v1" for now
on:
  push:
    branches:
      - enhance-v1 # specific branch

jobs:
  build:
    runs-on: alpine:latest

    steps:
      - name: Integrate and Deploy
        uses: actions/checkout@v4
        
      - name: Run a simple command
        run: echo "Hello, World! This action was triggered by a push to the enhance-v1 branch"

      # - name: Run build
      #   run: |
      #     echo "Running build process..."
      #     # Add your actual build commands here
